using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace NET6_Middlewares.CustomMiddlewares
{
    // You may need to install the Microsoft.AspNetCore.Http.Abstractions package into your project
    public class AutoGeneratedMiddleware
    {
        private readonly RequestDelegate _next;

        public AutoGeneratedMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public Task Invoke(HttpContext httpContext)
        {

            return _next(httpContext);
        }
    }

    // Extension method used to add the middleware to the HTTP request pipeline.
    public static class AutoGeneratedMiddlewareExtensions
    {
        public static IApplicationBuilder UseAutoGeneratedMiddleware(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<AutoGeneratedMiddleware>();
        }
    }
}
